// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvUjh9O3ssGtTlkU0irxbmHYdK3UxfE24',
    appId: '1:783038211695:web:48562971ad6a7674a40f9a',
    messagingSenderId: '783038211695',
    projectId: 'med-quiz-1df58',
    authDomain: 'med-quiz-1df58.firebaseapp.com',
    databaseURL: 'https://med-quiz-1df58-default-rtdb.firebaseio.com',
    storageBucket: 'med-quiz-1df58.appspot.com',
    measurementId: 'G-YBEEY2MLYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQZv9a952Qx9AGqw61sae7Es3Pya9IuTo',
    appId: '1:783038211695:android:260b8b32849508a6a40f9a',
    messagingSenderId: '783038211695',
    projectId: 'med-quiz-1df58',
    databaseURL: 'https://med-quiz-1df58-default-rtdb.firebaseio.com',
    storageBucket: 'med-quiz-1df58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEUkpQB_6x4U_pnkwk0bKIiwecBP1XsfM',
    appId: '1:783038211695:ios:4072a90032eea77ba40f9a',
    messagingSenderId: '783038211695',
    projectId: 'med-quiz-1df58',
    databaseURL: 'https://med-quiz-1df58-default-rtdb.firebaseio.com',
    storageBucket: 'med-quiz-1df58.appspot.com',
    androidClientId: '783038211695-2gmns4gs46hb8mqi30okcpl9s9lttt1v.apps.googleusercontent.com',
    iosClientId: '783038211695-n6rtnb7uemom9he2sagcrdbprl378dd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurdivia',
  );
}
